name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set commit hash
        run: echo "COMMIT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Log in to Docker Hub
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push Docker image

      - name: Build Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/ensf400-courseproject:${{ env.COMMIT_HASH }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/ensf400-courseproject:${{ env.COMMIT_HASH }} ${{ secrets.DOCKER_USERNAME }}/ensf400-courseproject:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ensf400-courseproject:${{ env.COMMIT_HASH }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ensf400-courseproject:latest